theme: jekyll-theme-slate
title: Welcome to Damian's Website! 
description: This Website will be used by me to learn how to use GitHub. During this process I will be most likely be powered by coffee and green tea.
